meta_name: "Therapiesgaia"
meta_title: "Therapiesgaia - Marvin Giomi"
meta_description: "Magnétiseur - rééquilibre des énergies - éviter les maladies "
meta_image: "logo1.png" # should exist in `app/assets/images/`
twitter_account: "@therapies_gaia"   # required for Twitter Cards
